### ISSUE TITLE
Config screen, role selection 

### ISSUE THREAD

**Issue by vinniebat** [vinniebat/SecretHitler#7]
When someone choses a fascist role in the ConfigScreen, let button appear where they mark the other fascists and hitler.
When the right amount of fasc are chosen, the other buttons should disappear.
When the right amount of fasc are chosen and you are hitler or one hitler is chosen, make create game clickable.

**Comment by CCookii** [comment]
See commit 74018a09b0ff4fee1f8fd073d23f7fb3b9e8c489
